In [29]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('IPL_Matches_tail_300.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,date,season,city,venue,team1,team2,toss_winner,toss_decision,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,winner_encoded
0,0,0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,...,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...",8
1,1,1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,...,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...",5
2,2,2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,...,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...",7
3,3,3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,...,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...",2
4,4,4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Royal Challengers Bengaluru,Lucknow Super Giants,Lucknow Super Giants,field,...,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...",9

In [30]:
data = df[['team1_runs' , 'team2_runs' , 'team1_wickets' , 'team2_wickets' , 'win_by_wickets']]
data.head()

   team1_runs  team2_runs  team1_wickets  team2_wickets  win_by_wickets
0       150.0       151.0              6              5               5
1       159.0       160.0              7              5               5
2       157.0       160.0              8              5               5
3       188.0       191.0              6              3               7
4       207.0       193.0              4              6               0

In [31]:

# find the relationship between every feature and the target domain ,  in IRL we use this with ML algorithms , but rn i havent learned it yet , so here we go

correlation = data.corr()
correlation

,team1_runs,team2_runs,team1_wickets,team2_wickets,win_by_wickets
team1_runs,1.000000,0.694777,-0.522805,0.388197,-0.378065
team2_runs,0.694777,1.000000,-0.270469,0.031346,0.095914
team1_wickets,-0.522805,-0.270469,1.000000,-0.192274,0.299937
team2_wickets,0.388197,0.031346,-0.192274,1.000000,-0.803569
win_by_wickets,-0.378065,0.095914,0.299937,-0.803569,1.000000

In [47]:
target_corr = correlation['team1_runs'].drop('team1_runs')
target_corr

team2_runs        0.694777
team1_wickets    -0.522805
team2_wickets     0.388197
win_by_wickets   -0.378065
Name: team1_runs, dtype: float64

# Forward selection

In [48]:
# arranging features from highest correlation to the lowest
target_corr = target_corr.reindex(
    target_corr.sort_values(ascending = False).index
)

target_corr

team2_runs        0.694777
team2_wickets     0.388197
win_by_wickets   -0.378065
team1_wickets    -0.522805
Name: team1_runs, dtype: float64

In [38]:
# forward selection

def forward_selection(correlation_series):

  best_Feature = correlation_series.idxmax()
  correlation_series = correlation_series.drop(best_Feature)

  return correlation_series , best_Feature

In [49]:
selected = []
remaining = target_corr.copy()

remaining , feature = forward_selection(remaining)
selected.append(feature)
print("selected feature : " , selected)
print("\n")
print("remaining feature :")

remaining

selected feature :  ['team2_runs']


remaining feature :

team2_wickets     0.388197
win_by_wickets   -0.378065
team1_wickets    -0.522805
Name: team1_runs, dtype: float64

In [50]:
remaining , feature = forward_selection(remaining)
selected.append(feature)
print("selected feature : " , selected)
print("\n")
print("remaining feature :")

remaining

selected feature :  ['team2_runs', 'team2_wickets']


remaining feature :

win_by_wickets   -0.378065
team1_wickets    -0.522805
Name: team1_runs, dtype: float64

In [51]:
remaining , feature = forward_selection(remaining)
selected.append(feature)
print("selected feature : " , selected)
print("\n")
print("remaining feature :")

remaining

selected feature :  ['team2_runs', 'team2_wickets', 'win_by_wickets']


remaining feature :

team1_wickets   -0.522805
Name: team1_runs, dtype: float64

# Backward elimination

In [52]:
# arranging features from lowest correlation to the highest
target_corr = target_corr.reindex(
    target_corr.sort_values(ascending = True).index
)

target_corr

team1_wickets    -0.522805
win_by_wickets   -0.378065
team2_wickets     0.388197
team2_runs        0.694777
Name: team1_runs, dtype: float64

In [53]:
def backward_elimination(correlation_series):
  least_feature = correlation_series.idxmin()
  correlation_series = correlation_series.drop(least_feature)

  return correlation_series , least_feature

In [54]:
remaining = target_corr.copy()
removed = []

remaining , feature = backward_elimination(remaining)
removed.append(feature)
print("\n removed features : " , removed)

print("\n remaining features : ")
remaining

 removed features :  ['team1_wickets']

 remaining features :

win_by_wickets   -0.378065
team2_wickets     0.388197
team2_runs        0.694777
Name: team1_runs, dtype: float64

In [55]:
remaining , feature = backward_elimination(remaining)
removed.append(feature)
print("\n removed features : " , removed)

print("\n remaining features : ")
remaining

 removed features :  ['team1_wickets', 'win_by_wickets']

 remaining features :

team2_wickets    0.388197
team2_runs       0.694777
Name: team1_runs, dtype: float64

In [56]:
remaining , feature = backward_elimination(remaining)
removed.append(feature)
print("\n removed features : " , removed)

print("\n remaining features : ")
remaining

 removed features :  ['team1_wickets', 'win_by_wickets', 'team2_wickets']

 remaining features :

team2_runs    0.694777
Name: team1_runs, dtype: float64