handling missing data using knn imputation

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('IPLPlayerStat.csv')
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,NaN,270,400,28,10.00,142.86,15.82,8.89,22.22,15.00,8,0
1,1,A Badoni,161,18,139,2.0,12,12,11,14.64,115.83,12.95,6.00,6.00,6.00,8,0
2,2,A Chandila,4,0,7,11.0,234,245,12,0.33,57.14,0.00,6.28,22.27,21.27,2,0
3,3,A Chopra,53,7,75,0.0,0,0,6,8.83,70.67,9.33,0.00,0.00,0.00,2,0
4,4,A Choudhary,25,2,20,5.0,108,144,5,5.00,125.00,10.00,8.00,28.80,21.60,0,0

In [9]:
df.isnull().sum()

Unnamed: 0             0
player                 0
runs                   0
boundaries             0
balls_faced            0
wickets                7
balls_bowled           0
runs_conceded          0
matches                0
batting_avg            0
batting_strike_rate    0
boundaries_percent     0
bowling_economy        0
bowling_avg            0
bowling_strike_rate    0
catches                0
stumpings              0
dtype: int64

In [10]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3 , weights='distance')
df['wickets'] = imputer.fit_transform(df[['wickets']])

In [11]:
df['wickets'].isnull().sum()

np.int64(0)

In [12]:
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,16.600334,270,400,28,10.00,142.86,15.82,8.89,22.22,15.00,8,0
1,1,A Badoni,161,18,139,2.000000,12,12,11,14.64,115.83,12.95,6.00,6.00,6.00,8,0
2,2,A Chandila,4,0,7,11.000000,234,245,12,0.33,57.14,0.00,6.28,22.27,21.27,2,0
3,3,A Chopra,53,7,75,0.000000,0,0,6,8.83,70.67,9.33,0.00,0.00,0.00,2,0
4,4,A Choudhary,25,2,20,5.000000,108,144,5,5.00,125.00,10.00,8.00,28.80,21.60,0,0

but data imputed is in decimals ( wickets are not decimals )

In [20]:
import numpy as np

df['wickets'] = np.ceil(df['wickets']).astype(int)
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,17,270,400,28,10.00,142.86,15.82,8.89,22.22,15.00,8,0
1,1,A Badoni,161,18,139,2,12,12,11,14.64,115.83,12.95,6.00,6.00,6.00,8,0
2,2,A Chandila,4,0,7,11,234,245,12,0.33,57.14,0.00,6.28,22.27,21.27,2,0
3,3,A Chopra,53,7,75,0,0,0,6,8.83,70.67,9.33,0.00,0.00,0.00,2,0
4,4,A Choudhary,25,2,20,5,108,144,5,5.00,125.00,10.00,8.00,28.80,21.60,0,0