In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('IPL_Matches_tail_300.csv')
df.head()

   Unnamed: 0  ...                                      team2_players
0           0  ...  YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...
1           1  ...  Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...
2           2  ...  JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...
3           3  ...  WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...
4           4  ...  Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...

[5 rows x 26 columns]

In [2]:
df['team1'].unique()

array(['Chennai Super Kings', 'Delhi Capitals', 'Sunrisers Hyderabad',
       'Rajasthan Royals', 'Royal Challengers Bengaluru',
       'Lucknow Super Giants', 'Punjab Kings', 'Mumbai Indians',
       'Kolkata Knight Riders', 'Gujarat Titans'], dtype=object)

In [4]:
df['winner'].value_counts()

winner
Gujarat Titans                 37
Royal Challengers Bengaluru    36
Punjab Kings                   29
Rajasthan Royals               29
Mumbai Indians                 27
Kolkata Knight Riders          27
Sunrisers Hyderabad            27
Chennai Super Kings            26
Lucknow Super Giants           25
Delhi Capitals                 25
Name: count, dtype: int64

In [5]:

# number of missing winners

df['winner'].isnull().sum()

np.int64(12)

In [8]:
df['winner'] = df['winner'].fillna('No result')
df['winner'].tail(10)

290          Kolkata Knight Riders
291                 Gujarat Titans
292            Sunrisers Hyderabad
293                   Punjab Kings
294               Rajasthan Royals
295                 Delhi Capitals
296    Royal Challengers Bengaluru
297               Rajasthan Royals
298                 Gujarat Titans
299                      No result
Name: winner, dtype: object

In [10]:
encoder = LabelEncoder()

df['winner_encoded'] = encoder.fit_transform(df['winner'])
df[['winner' , 'winner_encoded']].tail(15)

                          winner  winner_encoded
285        Kolkata Knight Riders               3
286  Royal Challengers Bengaluru               9
287               Delhi Capitals               1
288          Sunrisers Hyderabad              10
289             Rajasthan Royals               8
290        Kolkata Knight Riders               3
291               Gujarat Titans               2
292          Sunrisers Hyderabad              10
293                 Punjab Kings               7
294             Rajasthan Royals               8
295               Delhi Capitals               1
296  Royal Challengers Bengaluru               9
297             Rajasthan Royals               8
298               Gujarat Titans               2
299                    No result               6

In [13]:
mapping = pd.DataFrame({
    'winner' : encoder.classes_,
    'encoded value' : range(len(encoder.classes_))
})


mapping

                         winner  encoded value
0           Chennai Super Kings              0
1                Delhi Capitals              1
2                Gujarat Titans              2
3         Kolkata Knight Riders              3
4          Lucknow Super Giants              4
5                Mumbai Indians              5
6                     No result              6
7                  Punjab Kings              7
8              Rajasthan Royals              8
9   Royal Challengers Bengaluru              9
10          Sunrisers Hyderabad             10

In [14]:
df.to_csv('IPL_Matches_tail_300.csv')