In [1]:
import pandas as pd

df = pd.read_csv("IPL_Matches_tail_300.csv")
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,bat,150.0,6,...,5,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal..."
1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Delhi Capitals,Mumbai Indians,Mumbai Indians,field,159.0,7,...,5,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma..."
2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,bat,157.0,8,...,5,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga..."
3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Rajasthan Royals,Gujarat Titans,Gujarat Titans,field,188.0,6,...,7,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ..."
4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Royal Challengers Bangalore,Lucknow Super Giants,Lucknow Super Giants,field,207.0,4,...,0,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto..."

In [2]:
df['team1'].unique()

array(['Chennai Super Kings', 'Delhi Capitals', 'Sunrisers Hyderabad',
       'Rajasthan Royals', 'Royal Challengers Bangalore',
       'Lucknow Super Giants', 'Punjab Kings', 'Mumbai Indians',
       'Kolkata Knight Riders', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [5]:
columns_to_update = ['team1' , 'team2' , 'toss_winner' , 'winner']
old_name = 'Royal Challengers Bangalore'
new_name = 'Royal Challengers Bengaluru'

for col in columns_to_update :
  df[col] = df[col].replace(old_name , new_name)

df['team2'].unique()

array(['Rajasthan Royals', 'Mumbai Indians', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Royal Challengers Bengaluru',
       'Sunrisers Hyderabad', 'Chennai Super Kings'], dtype=object)

In [6]:
df.to_csv('IPL_Matches_tail_300.csv')

In [7]:
print(df['toss_decision'].unique())
print(df['team1'].nunique())
print(df['team2'].nunique())

['bat' 'field']
10
10

# Apply One hot encoding

In [8]:
df_encoded = pd.get_dummies(
    df,
    columns = ['team1' , 'team2' , 'toss_decision'],
    dtype = int
)

pd.set_option('display.max_columns' , None)

df_encoded.head(5)

,date,season,city,venue,toss_winner,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,team1_Chennai Super Kings,team1_Delhi Capitals,team1_Gujarat Titans,team1_Kolkata Knight Riders,team1_Lucknow Super Giants,team1_Mumbai Indians,team1_Punjab Kings,team1_Rajasthan Royals,team1_Royal Challengers Bengaluru,team1_Sunrisers Hyderabad,team2_Chennai Super Kings,team2_Delhi Capitals,team2_Gujarat Titans,team2_Kolkata Knight Riders,team2_Lucknow Super Giants,team2_Mumbai Indians,team2_Punjab Kings,team2_Rajasthan Royals,team2_Royal Challengers Bengaluru,team2_Sunrisers Hyderabad,toss_decision_bat,toss_decision_field
0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,150.0,6,151.0,5,Rajasthan Royals,complete,0,5,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...",1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Mumbai Indians,159.0,7,160.0,5,Mumbai Indians,complete,0,5,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...",0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,157.0,8,160.0,5,Punjab Kings,complete,0,5,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...",0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0
3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Gujarat Titans,188.0,6,191.0,3,Gujarat Titans,complete,0,7,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...",0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1
4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Lucknow Super Giants,207.0,4,193.0,6,Royal Challengers Bengaluru,complete,14,0,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1

In [10]:
df.shape

(300, 25)

In [9]:
df_encoded.shape

(300, 44)

drop first ( this will reduce the size and wont change meaning as well )

In [13]:
df_encoded2 = pd.get_dummies(
    df ,
    columns = ['team1' , 'team2' , 'toss_decision'],
    drop_first=True ,
    dtype = int
)

df_encoded2.head()

,date,season,city,venue,toss_winner,team1_runs,team1_wickets,team2_runs,team2_wickets,winner,result_type,win_by_runs,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,team1_Delhi Capitals,team1_Gujarat Titans,team1_Kolkata Knight Riders,team1_Lucknow Super Giants,team1_Mumbai Indians,team1_Punjab Kings,team1_Rajasthan Royals,team1_Royal Challengers Bengaluru,team1_Sunrisers Hyderabad,team2_Delhi Capitals,team2_Gujarat Titans,team2_Kolkata Knight Riders,team2_Lucknow Super Giants,team2_Mumbai Indians,team2_Punjab Kings,team2_Rajasthan Royals,team2_Royal Challengers Bengaluru,team2_Sunrisers Hyderabad,toss_decision_field
0,20-05-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,150.0,6,151.0,5,Rajasthan Royals,complete,0,5,R Ashwin,M Nayyar,CB Gaffaney,NA Patwardhan,YC Barde,PG Pathak,20,"RD Gaikwad, DP Conway, MM Ali, N Jagadeesan, A...","YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,21-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Mumbai Indians,159.0,7,160.0,5,Mumbai Indians,complete,0,5,JJ Bumrah,J Srinath,Nitin Menon,Tapan Sharma,HAS Khalid,GR Sadashiv Iyer,20,"PP Shaw, DA Warner, MR Marsh, RR Pant, SN Khan...","Ishan Kishan, RG Sharma, D Brevis, Tilak Varma...",1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,22-05-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,157.0,8,160.0,5,Punjab Kings,complete,0,5,Harpreet Brar,J Srinath,AK Chaudhary,NA Patwardhan,CB Gaffaney,Navdeep Singh,20,"PK Garg, Abhishek Sharma, RA Tripathi, AK Mark...","JM Bairstow, S Dhawan, M Shahrukh Khan, MA Aga...",0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
3,24-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Gujarat Titans,188.0,6,191.0,3,Gujarat Titans,complete,0,7,DA Miller,M Nayyar,BNJ Oxenford,VK Sharma,MA Gough,J Madanagopal,20,"YBK Jaiswal, JC Buttler, SV Samson, D Padikkal...","WP Saha, Shubman Gill, MS Wade, HH Pandya, DA ...",0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1
4,25-05-2022,2022,Kolkata,"Eden Gardens, Kolkata",Lucknow Super Giants,207.0,4,193.0,6,Royal Challengers Bengaluru,complete,14,0,RM Patidar,M Nayyar,J Madanagopal,MA Gough,BNJ Oxenford,VK Sharma,20,"V Kohli, F du Plessis, RM Patidar, GJ Maxwell,...","Q de Kock, KL Rahul, M Vohra, DJ Hooda, MP Sto...",0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1

In [14]:
df_encoded2.shape

(300, 41)

In [15]:
dropped_columns = set(df_encoded.columns) - set(df_encoded2.columns)
print(list(dropped_columns))

['team2_Chennai Super Kings', 'toss_decision_bat', 'team1_Chennai Super Kings']